// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chan_service.proto

package chan_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UnixTime             int64    `protobuf:"varint,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	ContainerName        string   `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ProtoName            string   `protobuf:"bytes,3,opt,name=proto_name,json=protoName,proto3" json:"proto_name,omitempty"`
	ClusterIp            string   `protobuf:"bytes,4,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Expiration           int64    `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	IsDelta              bool     `protobuf:"varint,7,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"`
	IsoTime              string   `protobuf:"bytes,8,opt,name=iso_time,json=isoTime,proto3" json:"iso_time,omitempty"`
	TmData               []byte   `protobuf:"bytes,20,opt,name=tm_data,json=tmData,proto3" json:"tm_data,omitempty"`
	SequenceId           uint64   `protobuf:"varint,21,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_280c724f64e655e4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func (m *Request) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *Request) GetProtoName() string {
	if m != nil {
		return m.ProtoName
	}
	return ""
}

func (m *Request) GetClusterIp() string {
	if m != nil {
		return m.ClusterIp
	}
	return ""
}

func (m *Request) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Request) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *Request) GetIsDelta() bool {
	if m != nil {
		return m.IsDelta
	}
	return false
}

func (m *Request) GetIsoTime() string {
	if m != nil {
		return m.IsoTime
	}
	return ""
}

func (m *Request) GetTmData() []byte {
	if m != nil {
		return m.TmData
	}
	return nil
}

func (m *Request) GetSequenceId() uint64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

type Response struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_280c724f64e655e4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *Response) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "chan_service.Request")
	proto.RegisterType((*Response)(nil), "chan_service.Response")
}

func init() { proto.RegisterFile("chan_service.proto", fileDescriptor_280c724f64e655e4) }

var fileDescriptor_280c724f64e655e4 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4b, 0x6b, 0x1b, 0x31,
	0x14, 0x85, 0x3b, 0x7e, 0xcc, 0xe3, 0xd6, 0xed, 0x42, 0xd4, 0xad, 0xfa, 0x1e, 0x0c, 0x85, 0x59,
	0x79, 0xd1, 0xee, 0xdb, 0x45, 0x0d, 0xc5, 0x8b, 0x86, 0xa0, 0x78, 0x2f, 0x94, 0x99, 0x8b, 0x23,
	0xb0, 0xa4, 0x89, 0x74, 0x1d, 0xfc, 0xd7, 0xf2, 0xef, 0xc2, 0x48, 0xb6, 0x71, 0xb2, 0xd4, 0x77,
	0xae, 0x74, 0x74, 0xcf, 0x01, 0xd6, 0xde, 0x29, 0x2b, 0x03, 0xfa, 0x07, 0xdd, 0xe2, 0xb2, 0xf7,
	0x8e, 0x1c, 0x9b, 0x5d, 0xb2, 0xc5, 0xe3, 0x08, 0x0a, 0x81, 0xf7, 0x7b, 0x0c, 0xc4, 0x3e, 0x43,
	0xb5, 0xb7, 0xfa, 0x20, 0x49, 0x1b, 0xe4, 0x59, 0x9d, 0x35, 0x63, 0x51, 0x0e, 0x60, 0xa3, 0x0d,
	0xb2, 0x1f, 0xf0, 0xb6, 0x75, 0x96, 0x94, 0xb6, 0xe8, 0xa5, 0x55, 0x06, 0xf9, 0xa8, 0xce, 0x9a,
	0x4a, 0xbc, 0x39, 0xd3, 0x2b, 0x65, 0x90, 0x7d, 0x05, 0x88, 0x36, 0x69, 0x64, 0x1c, 0x47, 0xaa,
	0x48, 0x4e, 0x72, 0xbb, 0xdb, 0x07, 0x42, 0x2f, 0x75, 0xcf, 0x27, 0x49, 0x3e, 0x92, 0x75, 0xcf,
	0xbe, 0x40, 0x35, 0xdc, 0x0b, 0xbd, 0x6a, 0x91, 0x4f, 0x93, 0x7a, 0x06, 0xec, 0x1b, 0x00, 0x1e,
	0x7a, 0xed, 0x15, 0x69, 0x67, 0x79, 0x1e, 0x3f, 0x78, 0x41, 0xd8, 0x47, 0x28, 0x75, 0x90, 0x1d,
	0xee, 0x48, 0xf1, 0xa2, 0xce, 0x9a, 0x52, 0x14, 0x3a, 0xac, 0x86, 0x63, 0x92, 0x5c, 0xda, 0xac,
	0x8c, 0xef, 0x16, 0x3a, 0xb8, 0xb8, 0xd8, 0x07, 0x28, 0xc8, 0xc8, 0x4e, 0x91, 0xe2, 0xef, 0xea,
	0xac, 0x99, 0x89, 0x9c, 0xcc, 0x4a, 0x91, 0x62, 0xdf, 0xe1, 0x75, 0x18, 0x92, 0xb1, 0x2d, 0x4a,
	0xdd, 0xf1, 0x79, 0x9d, 0x35, 0x13, 0x01, 0x27, 0xb4, 0xee, 0x16, 0xbf, 0xa1, 0x14, 0x18, 0x7a,
	0x67, 0x03, 0x0e, 0x06, 0x1e, 0x49, 0xb6, 0xae, 0x4b, 0xd1, 0x4d, 0x45, 0xe1, 0x91, 0xfe, 0xba,
	0x2e, 0x1a, 0x0c, 0x92, 0x09, 0xdb, 0x63, 0x64, 0xb9, 0x47, 0xfa, 0x1f, 0xb6, 0x3f, 0xff, 0xc1,
	0xe4, 0xda, 0x05, 0x62, 0x7f, 0x60, 0x76, 0x43, 0x1e, 0x95, 0xd9, 0x24, 0xe3, 0xf9, 0xf2, 0x59,
	0x6d, 0xc7, 0x7a, 0x3e, 0xbd, 0x7f, 0x89, 0x93, 0xf5, 0xe2, 0xd5, 0x6d, 0x1e, 0x03, 0xfe, 0xf5,
	0x14, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x43, 0x49, 0x30, 0xef, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	StreamTmData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) StreamTmData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/chan_service.Post/StreamTmData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	StreamTmData(context.Context, *Request) (*Response, error)
}

// UnimplementedPostServer can be embedded to have forward compatible implementations.
type UnimplementedPostServer struct {
}

func (*UnimplementedPostServer) StreamTmData(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamTmData not implemented")
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_StreamTmData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).StreamTmData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chan_service.Post/StreamTmData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).StreamTmData(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chan_service.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamTmData",
			Handler:    _Post_StreamTmData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chan_service.proto",
}
