// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usresil.proto

package usresiltm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RangingSuspended precede Databurst Suspended
type UsResilChanState int32

const (
	UsResilChanState_RANGING_SUSPENDED   UsResilChanState = 0
	UsResilChanState_DATABURST_SUSPENDED UsResilChanState = 1
	UsResilChanState_NORMAL_ONLINE       UsResilChanState = 2
)

var UsResilChanState_name = map[int32]string{
	0: "RANGING_SUSPENDED",
	1: "DATABURST_SUSPENDED",
	2: "NORMAL_ONLINE",
}

var UsResilChanState_value = map[string]int32{
	"RANGING_SUSPENDED":   0,
	"DATABURST_SUSPENDED": 1,
	"NORMAL_ONLINE":       2,
}

func (x UsResilChanState) String() string {
	return proto.EnumName(UsResilChanState_name, int32(x))
}

func (UsResilChanState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{0}
}

type UsChanState struct {
	UcId uint32 `protobuf:"varint,1,opt,name=UcId,proto3" json:"UcId,omitempty"`
	// use uint32 type to benefit ORCH side handle.
	State                uint32   `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsChanState) Reset()         { *m = UsChanState{} }
func (m *UsChanState) String() string { return proto.CompactTextString(m) }
func (*UsChanState) ProtoMessage()    {}
func (*UsChanState) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{0}
}

func (m *UsChanState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsChanState.Unmarshal(m, b)
}
func (m *UsChanState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsChanState.Marshal(b, m, deterministic)
}
func (m *UsChanState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsChanState.Merge(m, src)
}
func (m *UsChanState) XXX_Size() int {
	return xxx_messageInfo_UsChanState.Size(m)
}
func (m *UsChanState) XXX_DiscardUnknown() {
	xxx_messageInfo_UsChanState.DiscardUnknown(m)
}

var xxx_messageInfo_UsChanState proto.InternalMessageInfo

func (m *UsChanState) GetUcId() uint32 {
	if m != nil {
		return m.UcId
	}
	return 0
}

func (m *UsChanState) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type UsResilCm struct {
	SgId                  uint32   `protobuf:"varint,1,opt,name=SgId,proto3" json:"SgId,omitempty"`
	MdId                  uint32   `protobuf:"varint,2,opt,name=MdId,proto3" json:"MdId,omitempty"`
	CmMac                 string   `protobuf:"bytes,3,opt,name=CmMac,proto3" json:"CmMac,omitempty"`
	OrigTcs               []uint32 `protobuf:"varint,4,rep,packed,name=OrigTcs,proto3" json:"OrigTcs,omitempty"`
	RangingSuspendedTcs   []uint32 `protobuf:"varint,5,rep,packed,name=RangingSuspendedTcs,proto3" json:"RangingSuspendedTcs,omitempty"`
	DataBurstSuspendedTcs []uint32 `protobuf:"varint,6,rep,packed,name=DataBurstSuspendedTcs,proto3" json:"DataBurstSuspendedTcs,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UsResilCm) Reset()         { *m = UsResilCm{} }
func (m *UsResilCm) String() string { return proto.CompactTextString(m) }
func (*UsResilCm) ProtoMessage()    {}
func (*UsResilCm) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{1}
}

func (m *UsResilCm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilCm.Unmarshal(m, b)
}
func (m *UsResilCm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilCm.Marshal(b, m, deterministic)
}
func (m *UsResilCm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilCm.Merge(m, src)
}
func (m *UsResilCm) XXX_Size() int {
	return xxx_messageInfo_UsResilCm.Size(m)
}
func (m *UsResilCm) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilCm.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilCm proto.InternalMessageInfo

func (m *UsResilCm) GetSgId() uint32 {
	if m != nil {
		return m.SgId
	}
	return 0
}

func (m *UsResilCm) GetMdId() uint32 {
	if m != nil {
		return m.MdId
	}
	return 0
}

func (m *UsResilCm) GetCmMac() string {
	if m != nil {
		return m.CmMac
	}
	return ""
}

func (m *UsResilCm) GetOrigTcs() []uint32 {
	if m != nil {
		return m.OrigTcs
	}
	return nil
}

func (m *UsResilCm) GetRangingSuspendedTcs() []uint32 {
	if m != nil {
		return m.RangingSuspendedTcs
	}
	return nil
}

func (m *UsResilCm) GetDataBurstSuspendedTcs() []uint32 {
	if m != nil {
		return m.DataBurstSuspendedTcs
	}
	return nil
}

// Channel state in resilency CM
type UsResilCmChanState struct {
	SgId                 uint32         `protobuf:"varint,1,opt,name=SgId,proto3" json:"SgId,omitempty"`
	MdId                 uint32         `protobuf:"varint,2,opt,name=MdId,proto3" json:"MdId,omitempty"`
	CmMac                string         `protobuf:"bytes,3,opt,name=CmMac,proto3" json:"CmMac,omitempty"`
	TcsState             []*UsChanState `protobuf:"bytes,4,rep,name=TcsState,proto3" json:"TcsState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UsResilCmChanState) Reset()         { *m = UsResilCmChanState{} }
func (m *UsResilCmChanState) String() string { return proto.CompactTextString(m) }
func (*UsResilCmChanState) ProtoMessage()    {}
func (*UsResilCmChanState) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{2}
}

func (m *UsResilCmChanState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilCmChanState.Unmarshal(m, b)
}
func (m *UsResilCmChanState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilCmChanState.Marshal(b, m, deterministic)
}
func (m *UsResilCmChanState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilCmChanState.Merge(m, src)
}
func (m *UsResilCmChanState) XXX_Size() int {
	return xxx_messageInfo_UsResilCmChanState.Size(m)
}
func (m *UsResilCmChanState) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilCmChanState.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilCmChanState proto.InternalMessageInfo

func (m *UsResilCmChanState) GetSgId() uint32 {
	if m != nil {
		return m.SgId
	}
	return 0
}

func (m *UsResilCmChanState) GetMdId() uint32 {
	if m != nil {
		return m.MdId
	}
	return 0
}

func (m *UsResilCmChanState) GetCmMac() string {
	if m != nil {
		return m.CmMac
	}
	return ""
}

func (m *UsResilCmChanState) GetTcsState() []*UsChanState {
	if m != nil {
		return m.TcsState
	}
	return nil
}

type UsResilCmChanStateList struct {
	StateList            []*UsResilCmChanState `protobuf:"bytes,1,rep,name=StateList,proto3" json:"StateList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UsResilCmChanStateList) Reset()         { *m = UsResilCmChanStateList{} }
func (m *UsResilCmChanStateList) String() string { return proto.CompactTextString(m) }
func (*UsResilCmChanStateList) ProtoMessage()    {}
func (*UsResilCmChanStateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{3}
}

func (m *UsResilCmChanStateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilCmChanStateList.Unmarshal(m, b)
}
func (m *UsResilCmChanStateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilCmChanStateList.Marshal(b, m, deterministic)
}
func (m *UsResilCmChanStateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilCmChanStateList.Merge(m, src)
}
func (m *UsResilCmChanStateList) XXX_Size() int {
	return xxx_messageInfo_UsResilCmChanStateList.Size(m)
}
func (m *UsResilCmChanStateList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilCmChanStateList.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilCmChanStateList proto.InternalMessageInfo

func (m *UsResilCmChanStateList) GetStateList() []*UsResilCmChanState {
	if m != nil {
		return m.StateList
	}
	return nil
}

type UsResilStats struct {
	SgId                 uint32   `protobuf:"varint,1,opt,name=SgId,proto3" json:"SgId,omitempty"`
	MdId                 uint32   `protobuf:"varint,2,opt,name=MdId,proto3" json:"MdId,omitempty"`
	ResilCmCnt           uint32   `protobuf:"varint,3,opt,name=ResilCmCnt,proto3" json:"ResilCmCnt,omitempty"`
	TotalCmCnt           uint32   `protobuf:"varint,4,opt,name=TotalCmCnt,proto3" json:"TotalCmCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsResilStats) Reset()         { *m = UsResilStats{} }
func (m *UsResilStats) String() string { return proto.CompactTextString(m) }
func (*UsResilStats) ProtoMessage()    {}
func (*UsResilStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{4}
}

func (m *UsResilStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilStats.Unmarshal(m, b)
}
func (m *UsResilStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilStats.Marshal(b, m, deterministic)
}
func (m *UsResilStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilStats.Merge(m, src)
}
func (m *UsResilStats) XXX_Size() int {
	return xxx_messageInfo_UsResilStats.Size(m)
}
func (m *UsResilStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilStats.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilStats proto.InternalMessageInfo

func (m *UsResilStats) GetSgId() uint32 {
	if m != nil {
		return m.SgId
	}
	return 0
}

func (m *UsResilStats) GetMdId() uint32 {
	if m != nil {
		return m.MdId
	}
	return 0
}

func (m *UsResilStats) GetResilCmCnt() uint32 {
	if m != nil {
		return m.ResilCmCnt
	}
	return 0
}

func (m *UsResilStats) GetTotalCmCnt() uint32 {
	if m != nil {
		return m.TotalCmCnt
	}
	return 0
}

type UsResilStatsList struct {
	Stats                []*UsResilStats `protobuf:"bytes,1,rep,name=Stats,proto3" json:"Stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UsResilStatsList) Reset()         { *m = UsResilStatsList{} }
func (m *UsResilStatsList) String() string { return proto.CompactTextString(m) }
func (*UsResilStatsList) ProtoMessage()    {}
func (*UsResilStatsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{5}
}

func (m *UsResilStatsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilStatsList.Unmarshal(m, b)
}
func (m *UsResilStatsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilStatsList.Marshal(b, m, deterministic)
}
func (m *UsResilStatsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilStatsList.Merge(m, src)
}
func (m *UsResilStatsList) XXX_Size() int {
	return xxx_messageInfo_UsResilStatsList.Size(m)
}
func (m *UsResilStatsList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilStatsList.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilStatsList proto.InternalMessageInfo

func (m *UsResilStatsList) GetStats() []*UsResilStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type UsResilChanStats struct {
	SgId                 uint32   `protobuf:"varint,1,opt,name=SgId,proto3" json:"SgId,omitempty"`
	MdId                 uint32   `protobuf:"varint,2,opt,name=MdId,proto3" json:"MdId,omitempty"`
	UcId                 uint32   `protobuf:"varint,3,opt,name=UcId,proto3" json:"UcId,omitempty"`
	ResilCmCnt           uint32   `protobuf:"varint,4,opt,name=ResilCmCnt,proto3" json:"ResilCmCnt,omitempty"`
	TotalCmCnt           uint32   `protobuf:"varint,5,opt,name=TotalCmCnt,proto3" json:"TotalCmCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsResilChanStats) Reset()         { *m = UsResilChanStats{} }
func (m *UsResilChanStats) String() string { return proto.CompactTextString(m) }
func (*UsResilChanStats) ProtoMessage()    {}
func (*UsResilChanStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{6}
}

func (m *UsResilChanStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilChanStats.Unmarshal(m, b)
}
func (m *UsResilChanStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilChanStats.Marshal(b, m, deterministic)
}
func (m *UsResilChanStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilChanStats.Merge(m, src)
}
func (m *UsResilChanStats) XXX_Size() int {
	return xxx_messageInfo_UsResilChanStats.Size(m)
}
func (m *UsResilChanStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilChanStats.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilChanStats proto.InternalMessageInfo

func (m *UsResilChanStats) GetSgId() uint32 {
	if m != nil {
		return m.SgId
	}
	return 0
}

func (m *UsResilChanStats) GetMdId() uint32 {
	if m != nil {
		return m.MdId
	}
	return 0
}

func (m *UsResilChanStats) GetUcId() uint32 {
	if m != nil {
		return m.UcId
	}
	return 0
}

func (m *UsResilChanStats) GetResilCmCnt() uint32 {
	if m != nil {
		return m.ResilCmCnt
	}
	return 0
}

func (m *UsResilChanStats) GetTotalCmCnt() uint32 {
	if m != nil {
		return m.TotalCmCnt
	}
	return 0
}

type UsResilChanStatsList struct {
	Stats                []*UsResilChanStats `protobuf:"bytes,1,rep,name=Stats,proto3" json:"Stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UsResilChanStatsList) Reset()         { *m = UsResilChanStatsList{} }
func (m *UsResilChanStatsList) String() string { return proto.CompactTextString(m) }
func (*UsResilChanStatsList) ProtoMessage()    {}
func (*UsResilChanStatsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a720326322a45a, []int{7}
}

func (m *UsResilChanStatsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsResilChanStatsList.Unmarshal(m, b)
}
func (m *UsResilChanStatsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsResilChanStatsList.Marshal(b, m, deterministic)
}
func (m *UsResilChanStatsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsResilChanStatsList.Merge(m, src)
}
func (m *UsResilChanStatsList) XXX_Size() int {
	return xxx_messageInfo_UsResilChanStatsList.Size(m)
}
func (m *UsResilChanStatsList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsResilChanStatsList.DiscardUnknown(m)
}

var xxx_messageInfo_UsResilChanStatsList proto.InternalMessageInfo

func (m *UsResilChanStatsList) GetStats() []*UsResilChanStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterEnum("usresiltm.UsResilChanState", UsResilChanState_name, UsResilChanState_value)
	proto.RegisterType((*UsChanState)(nil), "usresiltm.UsChanState")
	proto.RegisterType((*UsResilCm)(nil), "usresiltm.UsResilCm")
	proto.RegisterType((*UsResilCmChanState)(nil), "usresiltm.UsResilCmChanState")
	proto.RegisterType((*UsResilCmChanStateList)(nil), "usresiltm.UsResilCmChanStateList")
	proto.RegisterType((*UsResilStats)(nil), "usresiltm.UsResilStats")
	proto.RegisterType((*UsResilStatsList)(nil), "usresiltm.UsResilStatsList")
	proto.RegisterType((*UsResilChanStats)(nil), "usresiltm.UsResilChanStats")
	proto.RegisterType((*UsResilChanStatsList)(nil), "usresiltm.UsResilChanStatsList")
}

func init() { proto.RegisterFile("usresil.proto", fileDescriptor_38a720326322a45a) }

var fileDescriptor_38a720326322a45a = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4d, 0xeb, 0xda, 0x40,
	0x10, 0xc6, 0xbb, 0x7f, 0xa3, 0x6d, 0xc6, 0x06, 0x74, 0x7d, 0x0b, 0x94, 0x16, 0xc9, 0x49, 0x0a,
	0x95, 0xd6, 0x16, 0x7a, 0xe8, 0x29, 0x1a, 0x91, 0x80, 0xc6, 0xb2, 0x49, 0xce, 0x92, 0x26, 0x21,
	0x0d, 0xd4, 0x28, 0xd9, 0xb5, 0x1f, 0xa1, 0xc7, 0x7e, 0xb1, 0x7e, 0xa9, 0xb2, 0x9b, 0x17, 0x13,
	0x23, 0x54, 0xe8, 0x6d, 0x67, 0x9e, 0x99, 0xc7, 0xf9, 0x8d, 0x13, 0x50, 0x2e, 0x34, 0x0d, 0x69,
	0xfc, 0x63, 0x7e, 0x4e, 0x4f, 0xec, 0x84, 0xe5, 0x3c, 0x64, 0x47, 0xed, 0x33, 0x74, 0x5d, 0xba,
	0xfa, 0xee, 0x25, 0x36, 0xf3, 0x58, 0x88, 0x31, 0x48, 0xae, 0x6f, 0x06, 0x2a, 0x9a, 0xa2, 0x99,
	0x42, 0xc4, 0x1b, 0x0f, 0xa1, 0x2d, 0x44, 0xf5, 0x49, 0x24, 0xb3, 0x40, 0xfb, 0x83, 0x40, 0x76,
	0x29, 0xe1, 0x36, 0xab, 0x23, 0xef, 0xb3, 0xa3, 0x6b, 0x1f, 0x7f, 0xf3, 0xdc, 0x2e, 0x30, 0x83,
	0xbc, 0x4d, 0xbc, 0xb9, 0xd7, 0xea, 0xb8, 0xf3, 0x7c, 0xb5, 0x35, 0x45, 0x33, 0x99, 0x64, 0x01,
	0x56, 0xe1, 0xf9, 0x3e, 0x8d, 0x23, 0xc7, 0xa7, 0xaa, 0x34, 0x6d, 0xcd, 0x14, 0x52, 0x84, 0xf8,
	0x3d, 0x0c, 0x88, 0x97, 0x44, 0x71, 0x12, 0xd9, 0x17, 0x7a, 0x0e, 0x93, 0x20, 0x0c, 0x78, 0x55,
	0x5b, 0x54, 0xdd, 0x93, 0xf0, 0x27, 0x18, 0x19, 0x1e, 0xf3, 0x96, 0x97, 0x94, 0xb2, 0x5a, 0x4f,
	0x47, 0xf4, 0xdc, 0x17, 0xb5, 0x5f, 0x08, 0x70, 0x49, 0x53, 0x5b, 0xc7, 0x7f, 0x60, 0x2d, 0xe0,
	0x85, 0xe3, 0xd3, 0x6c, 0x77, 0x9c, 0xab, 0xbb, 0x18, 0xcf, 0xcb, 0xcd, 0xcf, 0x2b, 0x6b, 0x27,
	0x65, 0x9d, 0xe6, 0xc2, 0xb8, 0x39, 0xc7, 0x36, 0xa6, 0x0c, 0x7f, 0x01, 0xb9, 0x0c, 0x54, 0x24,
	0xec, 0x5e, 0xd7, 0xec, 0x6e, 0xbb, 0xc8, 0xb5, 0x5e, 0xfb, 0x09, 0x2f, 0xf3, 0x02, 0x9e, 0xa3,
	0x0f, 0x83, 0xbd, 0x01, 0x28, 0x6c, 0x13, 0x26, 0xe8, 0x14, 0x52, 0xc9, 0x70, 0xdd, 0x39, 0x31,
	0x2f, 0xd7, 0xa5, 0x4c, 0xbf, 0x66, 0x34, 0x1d, 0x7a, 0xd5, 0xdf, 0x15, 0x20, 0xef, 0xb2, 0x7b,
	0xa2, 0x39, 0xc4, 0xa4, 0x09, 0x21, 0xe4, 0xec, 0xd0, 0xa8, 0xf6, 0x1b, 0x95, 0x1e, 0x05, 0xda,
	0xe3, 0xf3, 0x17, 0xf7, 0xdc, 0xaa, 0xdc, 0x73, 0x9d, 0x49, 0xfa, 0x07, 0x53, 0xbb, 0xc1, 0x64,
	0xc2, 0xf0, 0x76, 0x1e, 0xc1, 0xf5, 0xa1, 0xce, 0xf5, 0xea, 0xce, 0x9f, 0x53, 0xd4, 0xe7, 0x6c,
	0x6f, 0xdd, 0x06, 0x5a, 0x88, 0x47, 0xd0, 0x27, 0xba, 0xb5, 0x31, 0xad, 0xcd, 0xc1, 0x76, 0xed,
	0xaf, 0x6b, 0xcb, 0x58, 0x1b, 0xbd, 0x67, 0x78, 0x02, 0x03, 0x43, 0x77, 0xf4, 0xa5, 0x4b, 0x6c,
	0xa7, 0x22, 0x20, 0xdc, 0x07, 0xc5, 0xda, 0x93, 0x9d, 0xbe, 0x3d, 0xec, 0xad, 0xad, 0x69, 0xad,
	0x7b, 0x4f, 0xdf, 0x3a, 0xe2, 0x33, 0xff, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xb8, 0xf0,
	0x8b, 0xf7, 0x03, 0x00, 0x00,
}
